const { Category } = require ('../models');

const categoryData = [
    {
      category_name: "Sports",
      quote: "Yogi saw three of his players in the locker room wearing Cone Head hats. Yogi said.'Those guys make a pair'",
      description: "Show your team pride with official logos on all our Basics line."
    },
    {
      category_name: "The Basics",
      quote: "“When in doubt, wear a hat” — Mae West",
      description: "The Beanie, the Baseball Hat, the Bucket, the Outback and the Beret: these five hat-styles are our bestsellers, and no wonder! Casual and versatile, comfortable and practical, unisex and available in a wide variety of colours they represent affordable quality, and are sized for heads ranging from children’s XS to 3XL. Some of the most interest on our site is generated by our ability to embroider your hat with your favourite sports team or other totem, but when it comes to text, logos and customization, the possibilities are endless. We can stitch up to 8 colours in an area of 2.35” x 4.75”. The magic starts when you add the Basic Beanie, Basic Baseball, Basic Bucket, Basic Outback or Basic Beret for your shopping cart. Choices about colour, decorative add-ons and pre-set designs, custom text and logos will then follow. If you choose fully custom work, one of our team will contact you by email after your order is placed to obtain the png of your design (sorry, we can’t reproduce photographs, and please consider that thin lines and small details do not embroider well on rough surfaces). Check out what thread colours and fonts are available; you’ll be able to select those too. Basic hats that are plain or have a pre-set design ship out within 24 hours, custom orders usually in 2-3 days. Delivery within Canada takes about 7 days, 7-15 days to the US and 7-21 days worldwide."
    },
    {
      category_name: "Mostly Mens",
      quote: "“How a hat makes you feel is what a hat is all about.” Philip Treacy.",
      description: "Our signature collection brings together styles representative of each hat type: fedoras, trilbies, panamas, pork-pies, homburgs, boaters, newsboys (gatsbys), flat caps (driving hats/ascot caps/duckbills/ ivys), top hats and bowlers (which Americans call ‘derbies’). These styles are associated mostly with men, though in each case it is easy to think of women who have made the style their own. Rather than offer dozens of different duckbills and a plethora of panamas, we offer a curated collection of one to three models of each hat type—tested styles that look great on most. Every hat we sell, from basics to bespoke, displays high quality manufacture and our in-stock signatures ship out within 24 hours. Please consult our sizing chart. “A fine hat fits like a good friend” Charles M. Russel. If you haven’t found what you are looking for here, check out our specialty section where a few of the styles, like cowboy hats and mariners, are also great hats for every day wear in the right context."
    },
    {
      category_name: "Fabulously Feminine",
      quote: "“A woman can conquer the world with the right hat” —Kate Spade.",
      description: "Our signature collection brings together styles representative of each hat type. In the world of hats women enjoy a double privilege. They can revel in the fabulously feminine designs featured here (cloches, wide-brimmed sunhats, large crowned Kentucky Derby hats, fascinators, cocktail hats, button hats and headbands, turbans, pillboxes and perchers), and they can also look chic in the fedoras, trilbies, panamas, pork-pies, homburgs, boaters, newsboys (gatsbys), flat caps (driving hats/ascot caps/duckbills/ ivys), top hats and bowlers (which Americans call ‘derbies’) of the “mostly men’s” signature collection. Still not enough choice? Check out the cossack hats, cowboy hats, military and mariner hats that are part of our specialty section and which look great on women too. If you really can’t find your statement headpiece among our in-stock lines, you can engage our bespoke hat-making service. Unlike men’s styling where certain rules define each hat type, women’s designs are so variable that types, while they do exist, blur into each other. So we’ve kept the emphasis on just curating 18 of the most beautiful hats we could find—all rounders that will look good on 9 out of 10 female faces—made with care and attention and, as ever with our in-stock items, shipping out within 24 hours. Please consult our size chart if you are ordering a hat with a base versus a headband. “A piece of magic is a hat” Martha Sliter."
    },
    {
      category_name: "Specialty Hats",
      quote: "“It wasn't the wearing of the hat that counted so much as having one to wear. Every trade, every craft, [every culture] had its hat.” — Terry Pratchett",
      description: "It is the mission of our business to be the one-stop shopping destination for everything you can put on your head. Even though our basics collection, signatures collection and bespoke service provide pretty wide coverage of what’s available in the world of hats, we know that the world is a big place, so our Specialty Collection expands our world of hats to reflect an even greater diversity of international locations and specialized professions that may have a hat associated with them. Some are purely for fun, but most have an interesting cultural location or a serious job to do."
    },
    {
      category_name: "Bespoke Service",
      quote: "“Whenever you wear your hat your day will be special.” — Margo Nickel",
      description: "Our company can also create a one-of-a-kind hat just for you. This gallery of royals, race-goers, runway models and celebrity icons wearing hats of indelible memorability is provided for your pure joy and inspiration. Many of these hats are couture creations and cannot be replicated, but we are willing to make you a hat just as delicious especially for you. Our company employs individuals who have been taught the skilled trade of hat-making and who can show you a portfolio of their prior work. Their design sense and manufacture technique will make you a bespoke creation you will love for a lifetime. The process begins when you send us an email. Your personal hatter will contact you within 24 hours. You can decide how best to communicate with them. Often meeting by video call or sending a video to them of yourself doing a complete rotation can help them design a hat which will look fabulous from all angles. They will advise you about best styles for your facial type, discuss your favourite materials and designs as selected from the gallery here or sourced on your own, and teach you how to take accurate measurements if your hat is of a type that has a base. Then after 3-4 weeks spent making your hat, it will be shipped out to you by courier in crush-proof packaging. The service starts at $400 plus shipping. “Wearing hats has become like fine art for me” —Tina Brown"
    }
  ];

const seedCategories = () => Category.bulkCreate(categoryData);

module.exports = seedCategories; 