const { Product } = require ('../models');

const productData = [
  {
    name: "Beanie",
    quote: "'All those poor elves I haven’t set free yet, having to stay over during Christmas because there aren’t enough hats!' (J.K. Rowling Order of the Phoenix, spoken by Hermione whose goal, in support of elvish welfare, was to gift them all with knitted hats)",
    description: "Variously answering to the name of toque (Canada), wooly hat (Britain) or docker (the shallower style traditionally worn by dock workers), beanies are cozy and can be worn in a wide variety of ways to express your personality. Our rib-knit, 100% alpachino merino wool beanie, available in nine different colours, has a lot of slouch, so you can wear it uncuffed for a bit of droop at the back or thick-cuffed for a more upright look. Put a pom-pom on it or not. Customize with embroidery or applique, or have it plain. Any way you wear it, this hat is destined to become well-loved",
    price: 19.99,
    image1_url: "https://dropincoffee.com/cdn/shop/products/DSC_0252_540x.jpg?v=1653271679",
    image2_url: "https://www.churchmouseyarns.com/cdn/shop/files/SlouchyBasicBeanie_WATGAlpachinoMerino-1_gallery_1024x1024.jpg?v=1701301105",
    image3_url: "https://www.churchmouseyarns.com/cdn/shop/files/SlouchyBasicBeanie_WATGAlpachinoMerino-3_gallery_1024x1024.jpg?v=1701301105",
    image4_url: "https://images4-a.ravelrycache.com/uploads/tincanknits/915421821/BasicBeanie-TCK-9628-web_medium2.jpg",
    image5_url: "https://i.etsystatic.com/25287918/r/il/2140f2/5661828653/il_794xN.5661828653_abdp.jpg",
    num_in_stock: 50,
    rating: 4.5,
    num_of_reviews: 15,
    is_featured: true,
    category_id: 1
  },
  {
    name: "Baseball Hall",
    quote: "'Baseball caps never go out of style and are easy to wear. Beyond baseball, beyond sports, I really do think a baseball cap is for everyone -- David Wright'",
    description: "Visit our sports section to find your totemic, team-proclaiming lid, but everyone needs the casual style of this utility player in their wardrobe, sports fan or not. Snapbacks (the classic ones sold in our sports section with the adjustable plastic strap, stiff brim and structured crown) and truckers (also called gimmes or feed caps, the ones with the mesh at the back) are variations on this proven winner. Our draft pick here for the basics collection is a 100% washed cotton Dad's hat. Dad's hats are distinguished by their lower profile, more flexible curved brim and cloth strap adjuster. Of course Moms them too (and kids!). Available in 14 terrific colours, this hat looks great plain or with leather applique customized with your text, or custom embroidered with your text or logo.",
    price: 24.99,
    image1_url: "https://thehatdepot.com/cdn/shop/files/20230309_Shipify_Spring-Break_0011_Layer-4_800x_800x_f2c911ba-0164-4214-bb92-1a3e01fa0de7.jpg?v=1698936434",
    image2_url: "https://i.etsystatic.com/38145326/r/il/93a915/4972008084/il_794xN.4972008084_qabw.jpg",
    image3_url: "https://i.etsystatic.com/iap/2f7b3d/5628826069/iap_640x640.5628826069_tu3uvvr1.jpg?version=0",
    image4_url: "https://i.etsystatic.com/19999793/r/il/b80848/4193623937/il_794xN.4193623937_eqgr.jpg",
    image5_url: "https://i.etsystatic.com/37118102/r/il/44ad72/5077620589/il_794xN.5077620589_dg3g.jpg",
    num_in_stock: 80,
    rating: 4.7,
    num_of_reviews: 20,
    is_featured: true,
    category_id: 1
  },
  {
    name: "Beret",
    quote: "'I recommend the French beret, for it gives the impression of just the right soft toughness, a veritable wave of sophisticated brain matter. It is the kind of hat that inspires a person to grow into it, to become the person they never knew they could be.' ― Meia Geddes, Love Letters to the World",
    description: "Artists and soldiers have both done their part in popularizing the beret. Its French flair and sophistication are still felt (pun intended) (though Scots insist it is their own and call it the 'tam'), but it has been so successful in wooing wearers internationally that it has leapt from our specialty section to our basics collection -- a timeless best-seller. Our berets are made of wool felt, feature the traditional apple-stem top tassel, and rolled-under lip, which can be unrolled to create an entirely different look, and apple-stem finish at the top. In all, the beret can be styled at least 6 different ways. Multiply that by our whopping 27 different colour options and you have looks enough for a life-time. We offer six colours with a beautiful floral embroidery option, or we can embroider your beret with your own text or logo. The band circumference is significant for sizing so please check our sizing chart, comes in S-M-L",
    price: 29.99,
    image1_url: "https://i.pinimg.com/564x/d0/e1/c0/d0e1c0fa297b30d082a8440d08ef0518.jpg",
    image2_url: "https://i.pinimg.com/564x/c1/3a/ec/c13aec79ec9f772a34e83ee994fdf947.jpg",
    image3_url: "https://i.etsystatic.com/28905605/r/il/46ed72/4111161656/il_794xN.4111161656_9xkh.jpg",
    image4_url: "https://i.etsystatic.com/5414543/r/il/76aa33/5164004251/il_794xN.5164004251_1ap0.jpg",
    image5_url: "https://i.etsystatic.com/14281175/r/il/43d6d8/5456901757/il_794xN.5456901757_6bt1.jpg",
    num_in_stock: 40,
    rating: 4.8,
    num_of_reviews: 18,
    is_featured: true,
    category_id: 1
  },
  {
    name: "Bucket Hat",
    quote: "Stay cool and stylish with this trendy bucket hat.",
    description: "Stay cool and stylish with this trendy bucket hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    price: 21.99,
    image1_url: "https://i.pinimg.com/564x/b3/1b/5e/b31b5ebe772442ee992c4c22df4150e0.jpg",
    image2_url: "https://i.etsystatic.com/26678768/r/il/110051/4006721056/il_794xN.4006721056_th6x.jpg",
    image3_url: "https://i.etsystatic.com/26678768/r/il/110051/4006721056/il_794xN.4006721056_th6x.jpg",
    image4_url: null,
    image5_url: null,
    num_in_stock: 35,
    rating: 4.3,
    num_of_reviews: 12,
    is_featured: true,
    category_id: 1
  },
  {
    name: "Outback Hat",
    quote: "Explore the outdoors with this rugged and durable outback hat.",
    description: "Explore the outdoors with this rugged and durable outback hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    price: 27.99,
    image1_url: "https://i.pinimg.com/564x/14/8b/08/148b083bb041a4d5dffa53233c547f85.jpg",
    image2_url: "https://i.pinimg.com/564x/52/af/eb/52afeba67829045d26128d69005d8108.jpg",
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 25,
    rating: 4.2,
    num_of_reviews: 10,
    is_featured: true,
    category_id: 1
  },
  {
    name: "Bicorn",
    quote: "Add a touch of historical elegance with this distinctive bicorn hat.",
    description: "Add a touch of historical elegance with this distinctive bicorn hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    price: 32.99,
    image1_url: "https://i.pinimg.com/236x/fd/69/8f/fd698f3c5a709ed688d247ca380a0dd2.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 16,
    rating: 4.7,
    num_of_reviews: 23,
    is_featured: true,
    category_id: 1
  },
  {
    name: "Biretta",
    quote: "Enhance your attire with a touch of tradition using this distinctive biretta hat.",
    description: "Enhance your attire with a touch of tradition using this distinctive biretta hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    price: 34.99,
    image1_url: "https://i.pinimg.com/236x/b8/9c/d8/b89cd802efc006e07388874f3258b5e0.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 14,
    rating: 4.8,
    num_of_reviews: 27,
    is_featured: true,
    category_id: 1
  },
  {
    name: "Boonie",
    quote: "Stay cool in the great outdoors with this practical boonie hat.",
    description: "The brim is crucial, a bit narrower and floppier it could be a bucket hat, a bit more rigid it would outback, but the boonie has a distinct military heriage, being U.S. army issue to soldiers fighting in hot climates. The distinctive fabric loops around the crown are to accommodate foliage for camouflage and the hat is secured with a strap for stability. A great outdoors hat for those who like to hunt and fish, our mosquito hat is also a boonie.",
    price: 17.99,
    image1_url: "https://ah.houyhnhnm.jp/wp-content/uploads/2021/10/style63_7.jpg",
    image2_url: "https://i.pinimg.com/564x/c6/63/75/c663757c2d4c092b4bb45790bbdc380b.jpg",
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 28,
    rating: 4.2,
    num_of_reviews: 14,
    is_featured: false,
    category_id: 1
  },
  {
    name: "Chef's Hat",
    quote: "Cook with style and confidence in this classic chef's hat.",
    description: "Cook with style and confidence in this classic chef's hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    price: 14.99,
    image1_url: "https://i.pinimg.com/236x/9a/0e/fe/9a0efeceaac759e0732d6b4cab5b735a.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 35,
    rating: 4.5,
    num_of_reviews: 18,
    is_featured: false,
    category_id: 1
  },
  {
    name: "Conical Hat",
    quote: "Stay shaded in style with this unique conical hat.",
    description: "Stay shaded in style with this unique conical hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    price: 18.99,
    image1_url: "https://i.pinimg.com/564x/37/73/86/3773869dc45b9f72e26b0f3253c13fd3.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 30,
    rating: 4.0,
    num_of_reviews: 8,
    is_featured: false,
    category_id: 1
  },
  {
    name: "Cossack",
    quote: "Add a touch of Eastern European flair with this stylish cossack hat.",
    description: "Add a touch of Eastern European flair with this stylish cossack hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    price: 26.99,
    image1_url: "https://i.pinimg.com/564x/a4/a0/fd/a4a0fd46d16fc45939a150025825b111.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 22,
    rating: 4.0,
    num_of_reviews: 16,
    is_featured: true,
    category_id: 1
  },
  {
    name: "Cowboy Hat",
    quote: "Embrace the Wild West with this classic cowboy hat.",
    description: "Embrace the Wild West with this classic cowboy hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    price: 32.99,
    image1_url: "https://i.pinimg.com/736x/9c/f3/7b/9cf37b68f848b1fa4ea97bc82d1d7110.jpg",
    image2_url: "https://i.pinimg.com/564x/d4/df/75/d4df75637a1dc2f37497297958362a2d.jpg",
    image3_url: "https://i.pinimg.com/564x/07/88/f1/0788f1a4f6ec8974a7f0b502b0f96f06.jpg",
    image4_url: "https://i.pinimg.com/736x/bd/7f/e5/bd7fe570a8a7e5f565ddd053817d4ba8.jpg",
    image5_url: null,
    num_in_stock: 22,
    rating: 4.6,
    num_of_reviews: 16,
    is_featured: true,
    category_id: 1
  },
  {
    name: "Deerstalker",
    quote: "Channel your inner detective with this classic deerstalker hat.",
    description: "Channel your inner detective with this classic deerstalker hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    price: 32.99,
    image1_url: "https://i.pinimg.com/564x/44/62/53/446253f5a3cb20b4622ec60ffc2d3060.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 18,
    rating: 4.6,
    num_of_reviews: 13,
    is_featured: true,
    category_id: 1
  },
  {
    name: "Doctoral Hat",
    quote: "Celebrate your academic achievement with this elegant doctoral hat.",
    description: "Celebrate your academic achievement with this elegant doctoral hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    price: 45.99,
    image1_url: "https://commencement.utexas.edu/sites/default/files/doctoralregalia.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 15,
    rating: 4.8,
    num_of_reviews: 25,
    is_featured: true,
    category_id: 1
  },
  {
    "name": "Dread Net",
    "quote": "Rock the unique dread net for a distinctive look.",
    "description": "Rock the unique dread net for a distinctive look. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 23.99,
    "image1_url": "https://i.pinimg.com/736x/ba/84/43/ba8443e63d03e60671efa7c37c65214e.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 25,
    "rating": 4.1,
    "num_of_reviews": 11,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Fez",
    "quote": "Add a touch of mystique with this traditional fez.",
    "description": "Add a touch of mystique with this traditional fez. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 14.99,
    "image1_url": "https://i.pinimg.com/564x/18/e8/e8/18e8e8f191e2e8efff28ce2c053842ce.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 28,
    "rating": 3.9,
    "num_of_reviews": 14,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Hardhat",
    "quote": "Prioritize safety without compromising style with this durable hardhat.",
    "description": "Prioritize safety without compromising style with this durable hardhat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 18.99,
    "image1_url": "https://m.media-amazon.com/images/I/61QrsCK00PL._AC_UF350,350_QL80_.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 24,
    "rating": 4.0,
    "num_of_reviews": 10,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Joker Hat",
    "quote": "Channel your inner jester with this playful and vibrant joker hat.",
    "description": "Channel your inner jester with this playful and vibrant joker hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 21.99,
    "image1_url": "https://i.pinimg.com/564x/d8/bd/83/d8bd8352722d94c16c4236d7006173e0.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 27,
    "rating": 4.9,
    "num_of_reviews": 30,
    "is_featured": true,
    "category_id": 1
  },
  {
    "name": "Kippah",
    "quote": "Express your faith with this elegant and traditional kippah.",
    "description": "Express your faith with this elegant and traditional kippah. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 23.99,
    "image1_url": "https://i.pinimg.com/736x/4c/4f/18/4c4f1816eb0153550f5de9e8f3bf1a46.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 30,
    "rating": 4.5,
    "num_of_reviews": 22,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Kufi",
    "quote": "Embrace cultural diversity with this stylish and comfortable kufi.",
    "description": "Embrace cultural diversity with this stylish and comfortable kufi. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 19.99,
    "image1_url": "https://aragapparel.com/cdn/shop/products/IMG_0768_720x.jpg?v=1649016495",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 26,
    "rating": 4.4,
    "num_of_reviews": 15,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Mariner",
    "quote": "Sail the seas with confidence in this mariner.",
    "description": "Sail the seas with confidence in this mariner. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 26.99,
    "image1_url": "https://i.pinimg.com/564x/68/f9/8a/68f98a801fea8c83ca5972ecdf100063.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 18,
    "rating": 4.4,
    "num_of_reviews": 13,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Military Hat",
    "quote": "Show your respect for the armed forces with this classic military hat.",
    "description": "Show your respect for the armed forces with this classic military hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 34.99,
    "image1_url": "https://i.pinimg.com/564x/a3/45/82/a345829bf6ebb32825cab1ee1ea073f2.jpg",
    "image2_url": "https://i.pinimg.com/564x/e4/66/be/e466bec6196054a5829b8d6ef900222e.jpg",
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 18,
    "rating": 4.5,
    "num_of_reviews": 20,
    "is_featured": true,
    "category_id": 1
  },
  {
    "name": "Mosquito Net",
    "quote": "Stay protected from bugs with this practical mosquito net.",
    "description": "Stay protected from bugs with this practical mosquito net. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 20.99,
    "image1_url": "https://i.pinimg.com/236x/27/07/a8/2707a807a6c726c33a926588b0ce03c1.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 32,
    "rating": 4.2,
    "num_of_reviews": 17,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Pakol",
    "quote": "Stay warm and stylish with this traditional pakol.",
    "description": "Stay warm and stylish with this traditional pakol. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 23.99,
    "image1_url": "https://i.pinimg.com/564x/48/2d/78/482d78140baf93327b2e574993721a4a.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 25,
    "rating": 4.1,
    "num_of_reviews": 11,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Peruvian",
    "quote": "Experience warmth and style with this cozy peruvian hat.",
    "description": "Experience warmth and style with this cozy peruvian hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 20.99,
    "image1_url": "https://i.pinimg.com/236x/db/8a/62/db8a6252e249b228dc2ba50cc7256885.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 32,
    "rating": 4.2,
    "num_of_reviews": 17,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Phrygian",
    "quote": "Make a statement with this bold and iconic Phrygian hat.",
    "description": "Make a statement with this bold and iconic Phrygian hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 27.99,
    "image1_url": "https://i.pinimg.com/736x/77/e0/18/77e018f072b7a7c6569add6875522f1b.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 18,
    "rating": 4.7,
    "num_of_reviews": 20,
    "is_featured": true,
    "category_id": 1
  },
  {
    "name": "Regency Bonnet",
    "quote": "Embrace a charming and whimsical look with this lovely Regency bonnet.",
    "description": "Embrace a charming and whimsical look with this lovely Regency bonnet. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 26.99,
    "image1_url": "https://i.pinimg.com/564x/55/bf/9e/55bf9ec4080c1f9f8c7ab7e37e13e446.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 19,
    "rating": 4.4,
    "num_of_reviews": 14,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Safari Hat",
    "quote": "Embark on a stylish safari adventure with this trendy safari hat.",
    "description": "Embark on a stylish safari adventure with this trendy safari hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 29.99,
    "image1_url": "https://i.pinimg.com/736x/5d/ba/95/5dba95d8106eec4f3a8779d27b86b661.jpg",
    "image2_url": "https://i.pinimg.com/736x/9c/7a/ab/9c7aab7c0b8bc8d7057377748167c10d.jpgl",
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 22,
    "rating": 4.2,
    "num_of_reviews": 15,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "See You Jimmy Hat and Wig",
    "quote": "Bring joy and laughter to any occasion with this whimsical hat and wig combo.",
    "description": "Bring joy and laughter to any occasion with this whimsical hat and wig combo. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 19.99,
    "image1_url": "https://i.pinimg.com/564x/8b/59/e5/8b59e5e4a35006c12230a519bbf0e079.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 30,
    "rating": 4.9,
    "num_of_reviews": 28,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Soft Stovepipe",
    "quote": "Combine style and comfort with this fashionable soft stovepipe hat.",
    "description": "Combine style and comfort with this fashionable soft stovepipe hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 31.99,
    "image1_url": "https://i.pinimg.com/564x/70/66/d5/7066d5f4e5d0a07f737273e43f631fa2.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 22,
    "rating": 4.6,
    "num_of_reviews": 17,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Sombrero",
    "quote": "Bring the fiesta to life with this vibrant sombrero.",
    "description": "Bring the fiesta to life with this vibrant sombrero. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 28.99,
    "image1_url": "https://i.pinimg.com/564x/9f/7b/9c/9f7b9c397ae199fe57b8d75667257540.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 20,
    "rating": 4.9,
    "num_of_reviews": 22,
    "is_featured": true,
    "category_id": 1
  },
  {
    "name": "Surgeon's Cap",
    "quote": "Maintain a professional look in the operating room with this comfortable surgeon's cap.",
    "description": "Maintain a professional look in the operating room with this comfortable surgeon's cap. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 22.99,
    "image1_url": "https://i.pinimg.com/564x/d4/47/97/d44797bfd4f5f01f7aaf5bf2fd1a3d8b.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 25,
    "rating": 4.6,
    "num_of_reviews": 18,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Trapper hat",
    "quote": "Stay warm in cold weather with this stylish trapper hat.",
    "description": "Stay warm in cold weather with this stylish trapper hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 28.99,
    "image1_url": "https://i.pinimg.com/564x/c4/fe/bc/c4febc1259ce27e385d3c093d58b5293.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 20,
    "rating": 4.9,
    "num_of_reviews": 22,
    "is_featured": true,
    "category_id": 1
  },
  {
    "name": "Tricorn",
    "quote": "Embody the spirit of adventure with this classic tricorn.",
    "description": "Embody the spirit of adventure with this classic tricorn hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 29.99,
    "image1_url": "https://m.media-amazon.com/images/I/81s-2SAse9L._AC_SX679_.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 21,
    "rating": 4.6,
    "num_of_reviews": 18,
    "is_featured": false,
    "category_id": 1
  },
  {
    "name": "Turkey Hat",
    "quote": "Celebrate Thanksgiving in style with this festive turkey hat.",
    "description": "Celebrate Thanksgiving in style with this festive turkey hat. Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    "price": 15.99,
    "image1_url": "hhttps://i.pinimg.com/564x/a1/e9/ee/a1e9ee3473bae0c2bf84fe7ec4a14af8.jpg",
    "image2_url": null,
    "image3_url": null,
    "image4_url": null,
    "image5_url": null,
    "num_in_stock": 20,
    "rating": 4.3,
    "num_of_reviews": 21,
    "is_featured": false,
    "category_id": 1
  }
];

const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts; 

