const { Product } = require ('../models');

const productData = [
  {
    name: "Beanie",
    quote: "'All those poor elves I haven’t set free yet, having to stay over during Christmas because there aren’t enough hats!' (J.K. Rowling Order of the Phoenix, spoken by Hermione whose goal, in support of elvish welfare, was to gift every house elf with a knitted hats)",
    description: "Variously answering to the name of toque (Canada), wooly hat (Britain) or docker (the shallower style traditionally worn by dock workers), beanies are cozy knitted hats that can be worn in a wide variety of ways to express your personality. Our rib-knit, 100% alpachino merino wool beanie, available in nine different colours, and five sizes (please consult our chart for sizing), has a lot of slouch, so you can wear it uncuffed for a bit of droop at the back, or thick-cuffed for a more upright look. Put a pom-pom on it or not. Customize with embroidery or applique, or have it plain. Any way you wear it, this hat is destined to become part of you, well-loved and well-worn. All our beanies are cruelty-free and reflect our concern for elvish welfare.",
    price: 19.99,
    image1_url: "https://dropincoffee.com/cdn/shop/products/DSC_0252_540x.jpg?v=1653271679",
    image2_url: "https://www.churchmouseyarns.com/cdn/shop/files/SlouchyBasicBeanie_WATGAlpachinoMerino-1_gallery_1024x1024.jpg?v=1701301105",
    image3_url: "https://www.churchmouseyarns.com/cdn/shop/files/SlouchyBasicBeanie_WATGAlpachinoMerino-3_gallery_1024x1024.jpg?v=1701301105",
    image4_url: "https://images4-a.ravelrycache.com/uploads/tincanknits/915421821/BasicBeanie-TCK-9628-web_medium2.jpg",
    image5_url: "https://i.etsystatic.com/25287918/r/il/2140f2/5661828653/il_794xN.5661828653_abdp.jpg",
    num_in_stock: 50,
    rating: 4.86,
    num_of_reviews: 7,
    is_featured: true,
    category_id: 2
  },
  {
    name: "Baseball Hat",
    quote: "'Baseball caps never go out of style and are easy to wear. Beyond baseball, beyond sports, I really do think a baseball cap is for everyone -- David Wright'",
    description: "Visit our sports section to find your totemic, team-proclaiming lid, but everyone needs the casual style of this utility player, sports fan or not. Snapbacks (the classic ones sold in our sports section with the adjustable plastic strap, stiff brim and structured crown) and truckers (also called gimmes or feed caps, the ones with the mesh at the back) are variations on this proven winner. Our draft pick here for the basics collection is a 100% washed cotton Dad's hat. Dad's hats are distinguished by their lower profile, more flexible curved brim and cloth strap adjuster. Of course Moms love them too (and kids!). Available in 14 terrific colours, this hat looks great plain or with leather applique customized with your text, or custom embroidered with your text or logo.",
    price: 24.99,
    image1_url: "https://thehatdepot.com/cdn/shop/files/20230309_Shipify_Spring-Break_0011_Layer-4_800x_800x_f2c911ba-0164-4214-bb92-1a3e01fa0de7.jpg?v=1698936434",
    image2_url: "https://i.etsystatic.com/38145326/r/il/93a915/4972008084/il_794xN.4972008084_qabw.jpg",
    image3_url: "https://i.etsystatic.com/iap/2f7b3d/5628826069/iap_640x640.5628826069_tu3uvvr1.jpg?version=0",
    image4_url: "https://i.etsystatic.com/19999793/r/il/b80848/4193623937/il_794xN.4193623937_eqgr.jpg",
    image5_url: "https://i.etsystatic.com/37118102/r/il/44ad72/5077620589/il_794xN.5077620589_dg3g.jpg",
    num_in_stock: 80,
    rating: 5,
    num_of_reviews: 4,
    is_featured: true,
    category_id: 2
  },
  {
    name: "Beret",
    quote: "'I recommend the French beret, for it gives the impression of just the right soft toughness, a veritable wave of sophisticated brain matter. It is the kind of hat that inspires a person to grow into it, to become the person they never knew they could be.' ― Meia Geddes, Love Letters to the World",
    description: "Artists and soldiers have both done their part in popularizing the beret (known as a 'tam' in Scotland). The beret's French flair and sophistication are still felt (pun intended), but it has been so successful in wooing wearers internationally that it has leapt from our specialty section to our basics collection -- a timeless best-seller. Our berets are made of wool felt, feature the traditional apple-stem top tassel, and rolled-under lip, which can be unrolled to create an entirely different set of looks. In all, the beret can be styled at least 6 different ways. Multiply that by our whopping 27 different colour options and you have looks enough for a life-time. We offer six special colours with a beautiful floral embroidery option, or we can embroider your beret with your own text or logo. The band circumference is significant for sizing so please check our sizing chart, comes in S-M-L",
    price: 29.99,
    image1_url: "https://i.pinimg.com/564x/d0/e1/c0/d0e1c0fa297b30d082a8440d08ef0518.jpg",
    image2_url: "https://i.pinimg.com/564x/c1/3a/ec/c13aec79ec9f772a34e83ee994fdf947.jpg",
    image3_url: "https://i.etsystatic.com/28905605/r/il/46ed72/4111161656/il_794xN.4111161656_9xkh.jpg",
    image4_url: "https://i.etsystatic.com/5414543/r/il/76aa33/5164004251/il_794xN.5164004251_1ap0.jpg",
    image5_url: "https://i.etsystatic.com/14281175/r/il/43d6d8/5456901757/il_794xN.5456901757_6bt1.jpg",
    num_in_stock: 40,
    rating: 4.5,
    num_of_reviews: 4,
    is_featured: true,
    category_id: 2
  },
  {
    name: "Bucket Hat",
    quote: "'I kept buying bucket hats. Next thing I knew I felt like I didn't look right without one' -- Schoolboy Q",
    description: "Bucket hats (sometimes called fishing hats) originated around 1900 as a hat to keep Irish farmers and fishermen protected from the elements. The downward slant of the thin brim caused rain to run off and the lanolin in the wool felt or tweed which was their original material, made them naturally waterproof. Today they are more of a fashion statement, having been embraced in a big way by the hip hop community in the 1980s and being made now from a wide range of fabrics. Our 'basic bucket' is 100% cotton. Bucket hats are great sunhats for children as well as fashion accessories for adults. After selecting your hat in one of 12 colours you can customize it with a text or logo applique or apply embroidery directly to the hat. Please find your correct size using our sizing chart. We have XS-3X.",
    price: 21.99,
    image1_url: "https://i.pinimg.com/564x/60/d1/95/60d1951268d93f02a41d644dd24b2c31.jpg",
    image2_url: "https://i.pinimg.com/564x/86/3f/3f/863f3f79eba1214fa8c6a93026566b7b.jpg",
    image3_url: "https://i.etsystatic.com/25596895/r/il/7507a7/5606547766/il_794xN.5606547766_krnr.jpg",
    image4_url: "https://i.etsystatic.com/21548132/r/il/2144e3/5428093446/il_1140xN.5428093446_k8en.jpg",
    image5_url: "https://i.etsystatic.com/26678768/r/il/110051/4006721056/il_794xN.4006721056_th6x.jpg",
    num_in_stock: 35,
    rating: 4.67,
    num_of_reviews: 3,
    is_featured: true,
    category_id: 2
  },
  {
    name: "Outback Hat",
    quote: "Outback hats aren't worn out of necessity, but as clear fashion statements. The statement is: 'It's never too late to look like a cattle wrangler, even after the world has ended.' --Klavian",
    description: "The outback hat (sometimes called a safari hat, hiking hat, or traveler hat) is Australia's gift to the hat-wearing public. Wrangling cattle on an Australian ranch is only one of the adventuresome outdoor things you can do in it. The hardy construction makes it practically indestructible, a boast of which one name-brand manufacturer has made much. It can float if lost while white-water rafting, or be flattened for travelling without coming to any harm. The wide brim will protect you from the sun ...or from snakes that drop from trees. The brass grommets are for ventilation and the under chin strap will keep it secured through windy rides in the back of a landrover. This hat is not just a hat, but an attitude and a lifestyle. It is for the intrepid. Made of 100% cotton-canvas, we have six colours and the full range of sizes from XS-3X so please consult our sizing chart. Embroidered custom text and logos can be added.",
    price: 27.99,
    image1_url: "https://i.pinimg.com/564x/14/8b/08/148b083bb041a4d5dffa53233c547f85.jpg",
    image2_url: "https://i.pinimg.com/564x/52/af/eb/52afeba67829045d26128d69005d8108.jpg",
    image3_url: "https://i.pinimg.com/564x/d8/a9/19/d8a91957f69a16eac921f7d9a97f0776.jpg",
    image4_url: "https://www.sail.ca/media/catalog/product/t/i/tilley-ht8010_denim-blue__02.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=700&width=700&canvas=700:700",
    image5_url: "https://i.etsystatic.com/27498310/r/il/f81064/3635834156/il_794xN.3635834156_momf.jpg",
    num_in_stock: 25,
    rating: 5,
    num_of_reviews: 2,
    is_featured: true,
    category_id: 2
  },
  {
    name: "Bicorn",
    quote: "",
    description: "Trademark hat of a certain small Corsican who was tired of being overlooked. If that's a concern you share, buy this hat and the problem with vanish. Best worn sideways for full megalomaniac effect. May induce desire to invade Russia.",
    price: 32.99,
    image1_url: "https://i.pinimg.com/236x/fd/69/8f/fd698f3c5a709ed688d247ca380a0dd2.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 16,
    rating: 4.7,
    num_of_reviews: 23,
    is_featured: true,
    category_id: 5 
  },
  {
    name: "Biretta",
    quote: "",
    description: "We don't actually encourage ecclesiastical impersonation. People tend to get upset when you hear their confessions without actually being a priest. But in this genuine papal state biretta you'd totally be able to carry it off! This hat is known to date back to the 10th century, exact original purpose unknown, but it has long been synonymous with a traditional style of Catholicism. Made with care and finished with a hand-tufted pom pom.",
    price: 34.99,
    image1_url: "https://i.pinimg.com/236x/b8/9c/d8/b89cd802efc006e07388874f3258b5e0.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 14,
    rating: 4.8,
    num_of_reviews: 27,
    is_featured: true,
    category_id: 5
  },
  {
    name: "Boonie",
    quote: "Stay cool in the great outdoors with this practical boonie hat.",
    description: "The brim is crucial, a bit narrower and floppier it could be a bucket hat, a bit more rigid it would outback, but the boonie has a distinct military heritage, being U.S. army issue to soldiers fighting in hot climates. The distinctive fabric loops around the crown are to accommodate foliage for camouflage and the hat is secured with a strap for stability. A great outdoors hat for those who like to hunt and fish, our mosquito hat is also a boonie with netting attached.",
    price: 17.99,
    image1_url: "https://ah.houyhnhnm.jp/wp-content/uploads/2021/10/style63_7.jpg",
    image2_url: "https://i.pinimg.com/564x/c6/63/75/c663757c2d4c092b4bb45790bbdc380b.jpg",
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 28,
    rating: 4.2,
    num_of_reviews: 14,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Chef's Hat",
    quote: "",
    description: "Can't cook? Trouble boiling an egg? Then you need this hat. Dress for success in the kitchen and mislead your guests into believing you cooked a cordon bleu meal (which actually you ordered through Uber Eats). Remember to splash on a little tomato sauce and to swear temperamentally, just to really bolster the illusion.",
    price: 14.99,
    image1_url: "https://i.pinimg.com/236x/9a/0e/fe/9a0efeceaac759e0732d6b4cab5b735a.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 35,
    rating: 4.5,
    num_of_reviews: 18,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Conical Hat",
    quote: "",
    description: "The traditional hat of rice-harvesters in China, Japan and Vietnam, now co-opted by Mandarin restaurants for fete-ing birthday celebrants. Whatever your purpose in buying one, you'll find ours gives you the look.",
    price: 18.99,
    image1_url: "https://i.pinimg.com/564x/37/73/86/3773869dc45b9f72e26b0f3253c13fd3.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 30,
    rating: 4.0,
    num_of_reviews: 8,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Cossack",
    quote: "",
    description: "This hat evokes all the romance of old Russia. Imagine yourself skating on the Volga with Tchaikovsky's soaring violins as the soundtrack. For any cold climates this hat is eminently practical -- and beautiful. Made of peruvian alpacha wool, it looks like the finest fur but no animals were harmed in making it.",
    price: 26.99,
    image1_url: "https://i.pinimg.com/564x/a4/a0/fd/a4a0fd46d16fc45939a150025825b111.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 22,
    rating: 4.0,
    num_of_reviews: 16,
    is_featured: true,
    category_id: 5
  },
  {
    name: "Cowboy Hat",
    quote: "'If you're going to wear a cowboy hat, you're going to have to go all the way. You should have livestock around you, settle all of your disputes with a pistol, and ride a horse absolutely everywhere' -- Tom Segura. 'I never travel without my stetson' -- Larry Hagman",
    description: "Stetsons are the American version, invented in 1856 by a hat shop owner, in -- wait for it -- Philadelphia! In a short while the fashion became synonymous with the ranches, rodeos and romance of the American Plains. Akubras are the Australian equivalent. Today this standard piece of Western wear is popular as a hat style the world over with both dudes and gals. Ours is made from faux fur crushed into a fine felt and will look equally great on your trail-ride, or in your Calgary-based office tower.",
    price: 32.99,
    image1_url: "https://i.pinimg.com/736x/9c/f3/7b/9cf37b68f848b1fa4ea97bc82d1d7110.jpg",
    image2_url: "https://i.pinimg.com/564x/d4/df/75/d4df75637a1dc2f37497297958362a2d.jpg",
    image3_url: "https://i.pinimg.com/564x/07/88/f1/0788f1a4f6ec8974a7f0b502b0f96f06.jpg",
    image4_url: "https://i.pinimg.com/736x/bd/7f/e5/bd7fe570a8a7e5f565ddd053817d4ba8.jpg",
    image5_url: null,
    num_in_stock: 22,
    rating: 4.6,
    num_of_reviews: 16,
    is_featured: true,
    category_id: 5
  },
  {
    name: "Deerstalker",
    quote: "",
    description: "The game's afoot in our finest tweed deerstalker supplied by Christys of London. The truth is, Holmes mostly wore a top hat while coming and going from 221B, but while chasing spectral hounds on the Devonshire moor, he chose his deerstalker. This classic English hunting hat with its hallmark ear flaps tied on top that can be let down when the chilly mists sweep across the heath, reached its acme of popularity in the late 1800s. But give it a try. It's still a great hat, even for those not cosplaying the great detective.",
    price: 32.99,
    image1_url: "https://i.pinimg.com/564x/44/62/53/446253f5a3cb20b4622ec60ffc2d3060.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 18,
    rating: 4.6,
    num_of_reviews: 13,
    is_featured: true,
    category_id: 5
  },
  {
    name: "Doctoral Hat",
    quote: "",
    description: "Mortar boards are strictly for undergraduates. This soft velvet beefeater, with tassel worn to the left, is the prestige symbol of the higher-degree earner. You'll only be able to wear it once a year at commencement, but if you've already invested six figures and most of your youthful sanity in gaining your PhD, you surely can afford the hat. Hat's off to you -- you earned it!",
    price: 45.99,
    image1_url: "https://commencement.utexas.edu/sites/default/files/doctoralregalia.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 15,
    rating: 4.8,
    num_of_reviews: 25,
    is_featured: true,
    category_id: 5
  },
  {
    name: "Dread Net",
    quote: "",
    description: "Dreadlocks have religious significance for some Hindus and Rastafarians, but even those who choose the matted look as a fashion statement know that caring for one's locs is, in itself, an exercise of devotion. A dread net can definitely help. You don't always want them swinging onto the table when serving other people their jerk chicken. Our dread net, grey with rasta stripe (based on the colours of the Ethiopian flag), is one Bob Marley himself would be pleased to wear, and is guaranteed to do the job of keeping your locs locked away, while still announcing 'hey 'mon, I got me de hair!'",
    price: 23.99,
    image1_url: "https://i.pinimg.com/736x/ba/84/43/ba8443e63d03e60671efa7c37c65214e.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 25,
    rating: 4.1,
    num_of_reviews: 11,
    is_featured: false,
    category_id: 5
  },
  
  {
    name: "Fez",
    quote: "",
    description: "The fez, or in Arabic the tarboosh, hails from somewhere in North Africa or the Balkans. Turkey, Morocco, Tunisia, Greece, and Cyprus all lay claim to its origins. It plays a role in the military uniform of many of these countries, but also bears a resemblance to the higher style of kufi or muslim prayer hat. It became so identified with the religious but decadent final days of the Ottoman empire that outlawing it was one of Ataturk's moves toward secularizing Turkey in the early 20th century. When worn by English men in smoking jackets it signals sybaritic indulgence. When worn by hotel porters in North African hotels it suggests readiness to be of service. Whatever you intend by wearing a fez, it'll be a conversation starter for sure!",
    price: 14.99,
    image1_url: "https://i.pinimg.com/564x/18/e8/e8/18e8e8f191e2e8efff28ce2c053842ce.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 28,
    rating: 3.9,
    num_of_reviews: 14,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Hardhat",
    quote: "",
    description: "Our hard hat is serious enough for the job site, meeting all the professional standards as a bona fide piece of safety equipment. But if you'd prefer to capture that Freddy Mercury vibe, grab this hardhat, your speedos and a bottle of baby oil. Now you're ready for your next YMCA theme party.",
    price: 18.99,
    image1_url: "https://m.media-amazon.com/images/I/61QrsCK00PL._AC_UF350,350_QL80_.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 24,
    rating: 4.0,
    num_of_reviews: 10,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Joker Hat",
    quote: "",
    description: "Channel your inner jester with this playful and vibrant joker hat. Made of plush velvet and adorned with bells, you'll be the center of attention!",
    price: 21.99,
    image1_url: "https://i.pinimg.com/564x/d8/bd/83/d8bd8352722d94c16c4236d7006173e0.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 27,
    rating: 4.9,
    num_of_reviews: 30,
    is_featured: true,
    category_id: 5
  },
  {
    name: "Kippah",
    quote: "",
    description: "The Jewish kippah or yarmulke is a hat worn in synagogue by Jewish men, and occasionally women in the more modern branches of Judaism. By orthodox Jews it is worn all the time. A small piece of satin or felt, it nonetheless speaks volumes about the way one holds a Jewish identity. Show pride in your heritage with our beautiful handmade kippah.",
    price: 23.99,
    image1_url: "https://i.pinimg.com/736x/4c/4f/18/4c4f1816eb0153550f5de9e8f3bf1a46.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 30,
    rating: 4.5,
    num_of_reviews: 22,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Kufi",
    quote: "",
    description: "Also called a taqiyah or topi, there are various styles of this traditional men's head-covering in the muslim world. Generally speaking it is a brimless, rounded cap, often knitted or crocheted, worn for the 5X daily prayers and often throughout the whole of the day in devout countries.",
    price: 19.99,
    image1_url: "https://aragapparel.com/cdn/shop/products/IMG_0768_720x.jpg?v=1649016495",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 26,
    rating: 4.4,
    num_of_reviews: 15,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Mariner",
    quote: "",
    description: "Also commonly called a Greek Fisherman's Hat, we have opted for the neutral name 'mariner' because fishermen in Poland and Breton would also lay claim to this particular style. It's a stylish cap for men or women, and is one of the hat styles that looks very well on the more mature brow. Made from 100% wool, this is a solid piece of headwear that fulfills the practical purpose of keeping the head warm.",
    price: 26.99,
    image1_url: "https://i.pinimg.com/564x/68/f9/8a/68f98a801fea8c83ca5972ecdf100063.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 18,
    rating: 4.4,
    num_of_reviews: 13,
    is_featured: false,
    category_id: 5
  },  
  {
    name: "Military Hat",
    quote: "",
    description: "Worn by infantry and iconically associated with Fidel Castro, the military is a style of hat that features a shallow round cylinder attached to a beak at a regulation 90 degrees. It's a statement piece on women and looks good on men. We stock salt-and-pepper tweed ones and cotton-canvas ones in a range of colours.",
    price: 34.99,
    image1_url: "https://i.pinimg.com/564x/a3/45/82/a345829bf6ebb32825cab1ee1ea073f2.jpg",
    image2_url: "https://i.pinimg.com/564x/e4/66/be/e466bec6196054a5829b8d6ef900222e.jpg",
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 18,
    rating: 4.5,
    num_of_reviews: 20,
    is_featured: true,
    category_id: 5
  },
  {
    name: "Mosquito Net",
    quote: "",
    description: "Stay protected from bugs with this practical mosquito net attached to a boonie style hat. Great for fishermen or citizens of Northern Ontario.",
    price: 20.99,
    image1_url: "https://i.pinimg.com/236x/27/07/a8/2707a807a6c726c33a926588b0ce03c1.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 32,
    rating: 4.2,
    num_of_reviews: 17,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Pakol",
    quote: "",
    description: "A traditional woolen hat with rolled brim from Pakistan and Afghanistan. If we may express an opinion, this is a great hat-style, flattering to most faces, that should become more widely adopted around the world. It's also warm, being made of 100% kurk wool.",
    price: 23.99,
    image1_url: "https://i.pinimg.com/564x/48/2d/78/482d78140baf93327b2e574993721a4a.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 25,
    rating: 4.1,
    num_of_reviews: 11,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Peruvian",
    quote: "",
    description: "Here is South America's variation on the northern toque or beanie distinguished by long knitted flaps that hang down over the ears and end in tassels. Traditional ones like ours are knitted from 100% alpacha wool in the bright rainbow palette and decorated with tribal designs of llamas or other animals.",
    price: 20.99,
    image1_url: "https://i.pinimg.com/236x/db/8a/62/db8a6252e249b228dc2ba50cc7256885.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 32,
    rating: 4.2,
    num_of_reviews: 17,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Phrygian",
    quote: "",
    description: "This soft felt red hat with peak curved forward and long ear lugs looks like it should be worn by ill-tempered indentured gnomes, but in fact the Phrygian has been a sort of political statement hat through the ages by those who have valued freedom. Whether the Smurf hat is a white variant of the Phrygian is a topic of debate.",
    price: 27.99,
    image1_url: "https://i.pinimg.com/736x/77/e0/18/77e018f072b7a7c6569add6875522f1b.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 18,
    rating: 4.7,
    num_of_reviews: 20,
    is_featured: true,
    category_id: 5
  },
  {
    name: "Regency Bonnet",
    quote: "",
    description: "Charm your own Mr. Darcy by looking demure in this Regency Bonnet. The way these hats frame the feminine face and present it like a bouquet is so becoming that we doubt history is done with this particular style. Lead the resurgence by getting yours now.",
    price: 26.99,
    image1_url: "https://i.pinimg.com/564x/55/bf/9e/55bf9ec4080c1f9f8c7ab7e37e13e446.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 19,
    rating: 4.4,
    num_of_reviews: 14,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Safari Hat",
    quote: "",
    description: "Some would refer to the outback hat of our basics collection as a 'safari hat' but we prefer to reserve the name for these pith helmet style ones favoured in the days of big game hunting. The crown is hard to repel giraffe droppings if they fall on you from a great height, and there's a strap to keep it secured while you're running to escape a rhino.",
    price: 29.99,
    image1_url: "https://i.pinimg.com/736x/5d/ba/95/5dba95d8106eec4f3a8779d27b86b661.jpg",
    image2_url: "https://i.pinimg.com/736x/9c/7a/ab/9c7aab7c0b8bc8d7057377748167c10d.jpgl",
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 22,
    rating: 4.2,
    num_of_reviews: 15,
    is_featured: false,
    category_id: 5
  },
  {
    name: "See You Jimmy Hat and Wig",
    quote: "",
    description: "Trading on the fact that Glaswegian men can be called Jimmy, whether it is their name or not, an enterprising Scot invented the See You Jimmy hat and wig and it has risen to fame as one of the world's most beloved 'joke hats'. Just put this on and instantly bring laughter to any occasion. Better yet, put it on yer grannie! The swatch of ginger hair is attached. The hat itself is technically called a tamo-shanter or Scots bonnet.",
    price: 19.99,
    image1_url: "https://i.pinimg.com/564x/8b/59/e5/8b59e5e4a35006c12230a519bbf0e079.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 30,
    rating: 4.9,
    num_of_reviews: 28,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Sombrero",
    quote: "",
    description: "Enjoy a peaceful siesta under this traditional Mexican sombrero ('sombra' is Spanish for 'shade' and these hats with up to 2 foot brims cast quite a lot of it), or wait until evening and bring the fiesta to life. The straw material of our sombrero marks it as a hat for the common man (or woman), whereas Mexican gentlemen wore theirs in light-coloured felt. Pass the guacamole and strike up the mariachi band. Ole!",
    price: 28.99,
    image1_url: "https://i.pinimg.com/564x/9f/7b/9c/9f7b9c397ae199fe57b8d75667257540.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 20,
    rating: 4.9,
    num_of_reviews: 22,
    is_featured: true,
    category_id: 5
  },
  {
    name: "Surgeon's Cap",
    quote: "",
    description: "With our surgeon's cap you will 'cut' a fine figure (Groan!). Yes, we know there are stores that deal exclusively in medical uniforms, but if you want to buy your surgeon's cap from a full-service hat shop know that ours are the real McCoy, but the non-medically credentialed can also purchase them for your dorm wing's 'come as your favourite Grey's Anatomy character' theme party -- and yes we have cool prints like the ones Amelia Shepherd favours.",
    price: 22.99,
    image1_url: "https://i.pinimg.com/564x/d4/47/97/d44797bfd4f5f01f7aaf5bf2fd1a3d8b.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 25,
    rating: 4.6,
    num_of_reviews: 18,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Trapper hat",
    quote: "",
    description: "The trapper hat is sort of a Canadian version of the British deerstalker, in that its defining feature are the ear flaps that can be worn up or down. But this hat is hardcore, keeping ears from frostbite to 40 below. Our trapper is trimmed with faux fur but if you use it to check your own traps in the woods we won't judge.",
    price: 28.99,
    image1_url: "https://i.pinimg.com/564x/c4/fe/bc/c4febc1259ce27e385d3c093d58b5293.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 20,
    rating: 4.9,
    num_of_reviews: 22,
    is_featured: true,
    category_id: 5
  },
  {
    name: "Tricorn",
    quote: "",
    description: "Known as a cocked hat in its 18th-century heyday when it was a familiar piece of both military and civilian wear, the tricorn was featured in portraiture of the first 5 U.S. Presidents, and also in popular woodcuts of pirates. Our genuine leather 'pirate's hat' is a good cut above the typical costume variety and could proudly have been worn by Jack Sparrow himself. Unleash your inner  Arrrrrr!",
    price: 29.99,
    image1_url: "https://m.media-amazon.com/images/I/81s-2SAse9L._AC_SX679_.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 21,
    rating: 4.6,
    num_of_reviews: 18,
    is_featured: false,
    category_id: 5
  },
  {
    name: "Turkey Hat",
    quote: "",
    description: "If you want to bring instant joy and energy into a room, it's as simple as donning one of our plush poultry headdresses, reminiscent of the exploits of Mr. Bean at Christmas. Try it on your family this Thanksgiving.",
    price: 15.99,
    image1_url: "https://i.pinimg.com/564x/a1/e9/ee/a1e9ee3473bae0c2bf84fe7ec4a14af8.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 20,
    rating: 4.3,
    num_of_reviews: 21,
    is_featured: false,
    category_id: 5
  }, 
  {
    name: "Wonka Tophat",
    quote: "",
    description: "This is a proper-made Victorian top hat with a flared taper, but the purple colour makes it a little too 'novelty' to have made the cut for our 'mostly men's' line. You will certainly get noticed if you wear this hat. Great for street performers or those who lead ghostwalks or drive a haunted hearse. It's named, of course, for the fictional chocolatier Willy Wonka though neither the costume designers on the Gene Wilder classic nor the Johnny Depp remake had the genius to dress their hero in this exact hat.",
    price: 31.99,
    image1_url: "https://i.pinimg.com/736x/6f/86/74/6f867448170809e28e2f81896096520c.jpg",
    image2_url: null,
    image3_url: null,
    image4_url: null,
    image5_url: null,
    num_in_stock: 22,
    rating: 4.6,
    num_of_reviews: 17,
    is_featured: false,
    category_id: 5
  }
];

const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts; 

