const { Tag } = require('../models');

const tagData = [
  { tag_name: "Plain" },
  { tag_name: "Add pom-pom" },
  { tag_name: "Add applique text/logo" },
  { tag_name: "Add embroidered custom text" },
  { tag_name: "Add embroidered custom logo" },
  { tag_name: "Add embroidered custom text and logo" },
  { tag_name: "Lavender #B684B5" },
  { tag_name: "Slate Blue #2867A1" },
  { tag_name: "Seafoam #B6DCCF" },
  { tag_name: "Emerald #43A66E" },
  { tag_name: "Mustard #EDA400" },
  { tag_name: "Traffic Cone #EF5424" },
  { tag_name: "Raspberry #FF1493 " },
  { tag_name: "Black #000000" },
  { tag_name: "White #FFFFFF" },
  { tag_name: "Add embroidered custom text" },
  { tag_name: "Add embroidered custom logo" },
  { tag_name: "Add embroidered custom text and logo" },
  { tag_name: "One size -- adjustable by design" }, 
  { tag_name: "Army Green #505C52" },
  { tag_name: "Cyan Blue #434E68" },
  { tag_name: "Khaki #BCAA93" },
  { tag_name: "Gray #98999E" },
  { tag_name: "Yellow #CD9240" },
  { tag_name: "Pink #F19CBF" },
  { tag_name: "Burgundy #A24455" },
  { tag_name: "Purple #7D5B8B" },
  { tag_name: "Orange #E57369" },
  { tag_name: "Lake Blue #3E80B3" },
  { tag_name: "Coffee #594E4C" },
  { tag_name: "Blue #594E4C" },
  { tag_name: "Wool" },
  { tag_name: "Cotton" },
  { tag_name: "Wooly hat" },
  { tag_name: "Toque" },
  { tag_name: "Dad's hat" },
  { tag_name: "Trucker's hat" },
  { tag_name: "Snapback" },
  { tag_name: "Tam" },
  { tag_name: "Docker" },
  { tag_name: "French artist's hat" },
  { tag_name: "S-M-L" },
  { tag_name: "Blush #F28AB5" },
  { tag_name: "Magenta #9B076E" },
  { tag_name: "Sky #62A6EC" },
  { tag_name: "Navy #14274C" },
  { tag_name: "Hunter #152E32" },
  { tag_name: "Green #414C24" },
  { tag_name: "Celadon #90937B" },
  { tag_name: "Concrete #8DA0AF" },
  { tag_name: "Rock #8692A0" },
  { tag_name: "Charcoal #2B2A2C" }, 
  { tag_name: "Lemon #F9D510" },
  { tag_name: "Gold #F5AD07" },
  { tag_name: "Red #AB0217" },
  { tag_name: "Maroon #450920" },
  { tag_name: "Terra Cotta #7B2727" },
  { tag_name: "Espresso #32191C" },
  { tag_name: "Mocha #7C6058" },
  { tag_name: "Cafe Latte #B18567" },
  { tag_name: "Oatmeal #DFCACC" },
  { tag_name: "Off White #E4E7F9" },
  { tag_name: "Brick with Floral Embroidery #C22B0A" },
  { tag_name: "Green with Floral Embroidery #0E302C" },
  { tag_name: "Red with Floral Embroidery #C4021B" },
  { tag_name: "Black with Floral Embroidery #0B080D" },
  { tag_name: "Beige with Floral Embroidery #C3A79A" },
  { tag_name: "Cream with Floral Embroidery #D2CEBD" },
  { tag_name: "test"},
  { tag_name: "test2"},
  { tag_name: "With Custom Text" },
  { tag_name: "With Custom Logo" },
  { tag_name: "With Custom Text and Logo" },
  { tag_name: "With Decoration (floral embroidery)" },
  { tag_name: "Blue" },
  { tag_name: "Black" },
  { tag_name: "Purple" },
  { tag_name: "Yellow" },
  { tag_name: "Cerise" },
  { tag_name: "Green" }
];

const seedTags = () => Tag.bulkCreate(tagData);

module.exports = seedTags;


